name: TeaSpoon
main: CortexPE\TeaSpoon\Main
version: 2.0.0
api: 3.9.1
load: POSTWORLD
author: CortexPE
description: Implements integrated vanilla features into PocketMine-MP
website: https://github.com/CortexPE/TeaSpoon